# Generated by Django 3.0.5 on 2020-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure', '0005_auto_20200421_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='prediction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predict',
            name='probabiliy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
